#!/bin/sh
OIFS="`echo $IFS`"
if ! which git > /dev/null; then
  echo "There is no git command in your system, please install one."
  exit
fi
if [[ -d ~/.vim.old ]]; then
  rm -rf ~/.vim.old
fi
if [[ -f ~/.vimrc.old ]]; then
  rm -rf ~/.vimrc.old
fi
if [[ -d ~/.vim ]]; then
  mv ~/.vim ~/.vim.old
fi

if [[ -f ~/.vimrc ]]; then
  mv ~/.vimrc ~/.vimrc.old
fi

git clone git://github.com/stanleyz/vim.conf ~/.vim
ln -s ~/.vim/vimrc ~/.vimrc
cd ~/.vim
if [[ ! -d ~/.vim/bundle/vundle/.git ]]; then
  git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi
vim -c BundleInstall! -c q -c q -u bundles.vim
IFS="`echo $OIFS`"
