#!/bin/sh
OIFS="`echo $IFS`"
if ! which git > /dev/null; then
	echo "There is no git command in your system, please install one."
	exit
fi

if [[ -f ~/.stanley-vim ]]; then
	rm -rf ~/.stanley-vim
fi
if [[ -f ~/.vimrc.old ]]; then
	rm -rf ~/.vimrc.old
fi

if [[ -f ~/.vimrc ]]; then
	mv ~/.vimrc ~/.vimrc.old
fi
if [[ ! -d ~/.vim ]]; then
	mkdir ~/.vim
fi

#change screeen settings
if [[ -f ~/.screenrc.old ]]; then
	rm -rf ~/.screenrc.old
fi
if [[ -f ~/.screenrc ]]; then
	mv ~/.screenrc ~/.screenrc.old
fi

#change tmux settings
if [[ -f ~/.tmux.conf.old ]]; then
	rm -rf ~/.tmux.conf.old
fi
if [[ -f ~/.tmux.conf ]]; then
	mv ~/.tmux.conf ~/.tmux.conf.old
fi

git clone git://github.com/stanleyz/vim.conf ~/.stanley-vim
cp ~/.stanley-vim/vimrc ~/.vim/vimrc
cp ~/.stanley-vim/bundles.vim ~/.vim/bundles.vim
cp ~/.stanley-vim/bootstrap ~/.vim/bootstrap
cp ~/.stanley-vim/screenrc ~/.screenrc
cp ~/.stanley-vim/tmux.conf ~/.tmux.conf
rm -rf ~/.stanley-vim
ln -s ~/.vim/vimrc ~/.vimrc

cd ~/.vim
if [[ ! -d ~/.vim/bundle/vundle/.git ]]; then
	git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi
vim -c BundleInstall! -c q -c q -u bundles.vim
IFS="`echo $OIFS`"

echo -e "\n\n\033[33;31m Please ensure you have astyle / tidy / js-beautify installed for autoformat\n\n"
