hs.hotkey.bind({"alt"}, "j", function()
  hs.eventtap.keyStroke({""}, "down")
end)
hs.hotkey.bind({"alt"}, "h", function()
  hs.eventtap.keyStroke({""}, "left")
end)
hs.hotkey.bind({"alt"}, "k", function()
  hs.eventtap.keyStroke({""}, "up")
end)
hs.hotkey.bind({"alt"}, "l", function()
  hs.eventtap.keyStroke({""}, "right")
end)
hs.hotkey.bind({"alt"}, "u", function()
  hs.eventtap.keyStroke({""}, "home")
end)
hs.hotkey.bind({"alt"}, "p", function()
  hs.eventtap.keyStroke({""}, "end")
end)
hs.hotkey.bind({"alt"}, "i", function()
  hs.eventtap.keyStroke({""}, "pageup")
end)
hs.hotkey.bind({"alt"}, "o", function()
  hs.eventtap.keyStroke({""}, "pagedown")
end)
